apiVersion: v1
kind: Namespace
metadata:
  name: koogle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: koogle-deploy
  namespace: koogle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koogle-api
  template:
    metadata:
      labels:
        app: koogle-api
    spec:
      containers:
      - name: koogle-api
        image: workirostub/koogle:api-server
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred