name: notify completed

on:
  workflow_run:
    workflows: [ci]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELE_BOT_CHANNEL }}
          token: ${{ secrets.TELE_BOT_TOKEN }}
          message: |
            빌드가 성공했습니다!
            Commit message: ${{github.event.head_commit.message}}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Author: [${{github.event.head_commit.author.name}}](https://github.com/${{github.actor}})
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELE_BOT_CHANNEL }}
          token: ${{ secrets.TELE_BOT_TOKEN }}
          message: |
            빌드가 실패했습니다...
            Commit message: ${{github.event.head_commit.message}}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Author: [${{github.event.head_commit.author.name}}](https://github.com/${{github.actor}})